performance = "High"
theme = "dracula"
padding-x = 0

[fonts]
size = 19

[fonts.regular]
family = "JetBrains Mono"
style = "normal"
weight = 400

[fonts.bold]
family = "JetBrains Mono"
style = "normal"
weight = 700

[fonts.italic]
family = "JetBrains Mono"
style = "italic"
weight = 300

[fonts.bold-italic]
family = "JetBrains Mono"
style = "italic"
weight = 700

# Navigation
#
# "mode" - Define navigation mode: CollapsedTab, BottomTab, TopTab, Breadcrumb.
# "clickable" - Enable click on tabs to switch.
# "use-current-path" - Use same path whenever a new tab is created.
# "color-automation" - Set a specific color for the tab whenever a specific program is running.
# "macos-hide-window-buttons" - (MacOS only) Hide window buttons
#
[navigation]
mode = "BottomTab"
clickable = false
use-current-path = true
color-automation = [
  { program = "nvim", color = "#FFFF00" }
]

disable-renderer-when-unfocused = false

# Use fork
#
# Defaults for POSIX-based systems (Windows is not configurable):
# MacOS: spawn processes
# Linux/BSD: fork processes
#
use-fork = false

[developer]
# Log level
#
# This property enables log level filter. Default is "OFF".
log-level = "INFO"
